# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{git_pivotal_tracker_x}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Philippe Huibonhoa"]
  s.date = %q{2011-10-27}
  s.description = %q{Provides a set of git workflow tools to start and finish Pivotal Tracker stories in topic branches}
  s.email = %q{phuibonhoa@gmail.com}
  s.executables = ["commit-msg", "git-bug", "git-chore", "git-feature", "git-finish", "git-info", "git-story"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".rvmrc",
    "Gemfile",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/commit-msg",
    "bin/git-bug",
    "bin/git-chore",
    "bin/git-feature",
    "bin/git-finish",
    "bin/git-info",
    "bin/git-story",
    "cucumber.yml",
    "features/diagnostics.feature",
    "features/getting_started.feature",
    "features/hooks/aruba.rb",
    "features/step_definitions/git_steps.rb",
    "features/support/env.rb",
    "git_pivotal_tracker_x.gemspec",
    "lib/git_pivotal_tracker.rb",
    "lib/git_pivotal_tracker/base.rb",
    "lib/git_pivotal_tracker/finish.rb",
    "lib/git_pivotal_tracker/info.rb",
    "lib/git_pivotal_tracker/story.rb",
    "spec/fixtures/finish_story.xml",
    "spec/fixtures/no_stories.xml",
    "spec/fixtures/one_story.xml",
    "spec/fixtures/project.xml",
    "spec/fixtures/start_story.xml",
    "spec/fixtures/story.xml",
    "spec/git_pivotal_tracker/base_spec.rb",
    "spec/git_pivotal_tracker/finish_spec.rb",
    "spec/git_pivotal_tracker/info_spec.rb",
    "spec/git_pivotal_tracker/story_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/phuibonhoa/git_pivotal_tracker}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{A git workflow integrated with Pivotal Tracker}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<grit>, [">= 0"])
      s.add_runtime_dependency(%q<pivotal-tracker>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
      s.add_development_dependency(%q<webmock>, [">= 0"])
    else
      s.add_dependency(%q<grit>, [">= 0"])
      s.add_dependency(%q<pivotal-tracker>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<cucumber>, [">= 0"])
      s.add_dependency(%q<webmock>, [">= 0"])
    end
  else
    s.add_dependency(%q<grit>, [">= 0"])
    s.add_dependency(%q<pivotal-tracker>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<cucumber>, [">= 0"])
    s.add_dependency(%q<webmock>, [">= 0"])
  end
end

